### ISSUE TITLE
problem in run project

### ISSUE THREAD

**Issue by parimahziyi** [bedus-creation/Shopping-Sahuba#19]
Hi 
I can't run your project. 
i have these error:

Warning: require_once(C:\Users\Pasargad-Pc\Desktop\New folder (3)\Shopping-Sahuba/public/index.php): failed to open stream: No such file or directory in C:\Users\Pasargad-Pc\Desktop\New folder (3)\Shopping-Sahuba\server.php on line 21

Fatal error: require_once(): Failed opening required 'C:\Users\Pasargad-Pc\Desktop\New folder (3)\Shopping-Sahuba/public/index.php' (include_path='C:\xampp\php\pear') in C:\Users\Pasargad-Pc\Desktop\New folder (3)\Shopping-Sahuba\server.php on line 21
help me plz

**Comment by bedus-creation** [comment]
change public_html folder name into public

**Comment by parimahziyi** [comment]
thanks a lot for your answer. I change it. but unfortunately, I face this: 500
Whoops, something went wrong on our servers.
also before your guidance, I follow this page: https://stackoverflow.com/questions/30873773/laravel5-chdir-no-such-file-or-directory-errno-2
but nothing happened...
help me plz.

**Comment by parimahziyi** [comment]
let me add that I had this error after database seed when I run php artisan serve:
 31|      * @throws \Exception
    32|      */
    33|     public function handle()
    34|     {
  > 35|         chdir(public_path());
    36| 
    37|         $this->line("Laravel development server started: <http://{$this->host()}:{$this->port()}>");
    38| 
    39|         passthru($this->serverCommand(), $status);


so i changed :
//        chdir(public_path());
        chdir('/');
according to link  but again that I faced error as I said in the first comment

**Comment by bedus-creation** [comment]
To run project successfully
1. clone the project git clone git@github.com:bedus-creation/Shopping-Sahuba.git
2. change public_html folder name into public
3. change .env example to .env
4. Generate app key
```
php artisan key:generate
```
5. setup database credentials
6. Install dependecies
```
composer install 
```
7. run the project
